services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    image: vildly-rag-bot:latest
    container_name: vildly-rag-bot

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_FILE: /app/data/users.db

    volumes:
      - vildly_data:/app/data

volumes:
  vildly_data: