name: Start tests and deploy
on:
  push:
    branches:
      [Week7]
  pull_request:
    branches:
      [main, Week7]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [15, 16, 20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
        -run: npm ci
        -run: 
          npm run build
          npm test
